### ISSUE TITLE
Conflicting option name --version

### ISSUE THREAD

**Issue by pumazi** [karenc/db-migrator#16]
``--version`` is used both to state the version of the db-migrator application and the version to init or migrate. Let's pick one or the other.

**Comment by karenc** [comment]
I thought I've fixed the problem. (`--version` not working for `dbmigrator migrate`) :cold_sweat: 

Any suggestions on how to change it?

**Comment by pumazi** [comment]
Use ``-V`` for version?

**Comment by karenc** [comment]
`-v` is already used for verbose.

**Comment by karenc** [comment]
`-V` for version then :bulb:

**Comment by karenc** [comment]
Oh that's what you said... :+1:
