### ISSUE TITLE
Multiple migration directories within the same environment

### ISSUE THREAD

**Issue by pumazi** [karenc/db-migrator#6]
Which migration directory is found when there is more than one migration_directory entry-point registered in an environment? For example, if cnx-archive and cnx-publishing are installed in the same python environment, whichever entry-point is found last will be the one to set the value for migration_directory.

**Comment by pumazi** [comment]
I believe the solution to this problem is to contextualize the runtime of db-migrator. Basically, answer the question: **What is the best way to specify the context of the migration?**

**Comment by karenc** [comment]
I think this only became a problem when we started using entry points. Is it really a good idea? 

My suggestion is to add an extra argument, like `db-migrator migrate cnx-archive`

**Comment by karenc** [comment]
Please have a look at #7 to see if you think it's ok.
